import * as THREE from 'three';
import { enhanceMaterialWithDarkness, loadGltfScene, loadTexture } from '../../models.js';

/**
 * Level 5 materials, canvas textures, and props. Textures are generated by
 * scripts/generate-hotel-assets.mjs from CC0 scans; models are CC0 Poly Haven assets.
 */

export const TEXTURE_TILE = { carpet: 1.2, damask: 0.9, plaster: 2 };
export const ROOM_NUMBER_COLUMNS = 4;
export const ROOM_NUMBER_ROWS = 10;
export const ROOM_NUMBER_CELLS = ROOM_NUMBER_COLUMNS * ROOM_NUMBER_ROWS;
const PORTRAIT_VARIANTS = 3;

let resources = null;
let loading = null;
const darkenableMaterials = [];
const portraitMaterials = [];

function seededRandom(seed) {
    let state = seed >>> 0;
    return () => {
        state = (state * 1664525 + 1013904223) >>> 0;
        return state / 4294967296;
    };
}

function canvasTexture(canvas) {
    const texture = new THREE.CanvasTexture(canvas);
    texture.colorSpace = THREE.SRGBColorSpace;
    texture.anisotropy = 4;
    return texture;
}

// Room numbers are never in sequence on Level 5; a few are numbers nobody should see.
function roomNumbers() {
    const random = seededRandom(505);
    const strange = ['382', '0', '13', '5', '1920', '???', '-1'];
    return Array.from({ length: ROOM_NUMBER_CELLS }, (_, index) => {
        if (index % 6 === 5) return strange[Math.trunc(index / 6) % strange.length];
        const digits = random() < 0.6 ? 3 : 4;
        return String(Math.floor(10 ** (digits - 1) + random() * 9 * 10 ** (digits - 1)));
    });
}

function createRoomNumberAtlas() {
    const canvas = document.createElement('canvas');
    canvas.width = 1024;
    canvas.height = 1024;
    const context = canvas.getContext('2d');
    const cellWidth = canvas.width / ROOM_NUMBER_COLUMNS;
    const cellHeight = canvas.height / ROOM_NUMBER_ROWS;
    const numbers = roomNumbers();
    context.textAlign = 'center';
    context.textBaseline = 'middle';
    numbers.forEach((number, index) => {
        const x = (index % ROOM_NUMBER_COLUMNS) * cellWidth;
        const y = Math.floor(index / ROOM_NUMBER_COLUMNS) * cellHeight;
        const brass = context.createLinearGradient(x, y, x, y + cellHeight);
        brass.addColorStop(0, '#e2c27a');
        brass.addColorStop(0.5, '#b58a43');
        brass.addColorStop(1, '#7d5a26');
        context.fillStyle = brass;
        context.fillRect(x, y, cellWidth, cellHeight);
        context.strokeStyle = '#5a3f18';
        context.lineWidth = 6;
        context.strokeRect(x + 8, y + 8, cellWidth - 16, cellHeight - 16);
        context.font = 'bold 58px Georgia, "Times New Roman", serif';
        context.fillStyle = '#f5dfa6';
        context.fillText(number, x + cellWidth / 2 + 2, y + cellHeight / 2 + 3);
        context.fillStyle = '#2e1d08';
        context.fillText(number, x + cellWidth / 2, y + cellHeight / 2);
    });
    return canvasTexture(canvas);
}

function createExitTexture() {
    const canvas = document.createElement('canvas');
    canvas.width = 256;
    canvas.height = 112;
    const context = canvas.getContext('2d');
    context.fillStyle = '#1c0303';
    context.fillRect(0, 0, 256, 112);
    context.strokeStyle = '#6e0c08';
    context.lineWidth = 6;
    context.strokeRect(6, 6, 244, 100);
    context.font = 'bold 70px "Arial Narrow", Arial, sans-serif';
    context.textAlign = 'center';
    context.textBaseline = 'middle';
    context.shadowColor = '#ff2a12';
    context.shadowBlur = 18;
    context.fillStyle = '#ff5238';
    context.fillText('EXIT', 128, 60);
    return canvasTexture(canvas);
}

// Dim oil portraits for the gilt frames. The eyes are a separate emissive mask.
function createPortrait(seed) {
    const random = seededRandom(seed);
    const width = 384;
    const height = 296;
    const paint = document.createElement('canvas');
    paint.width = width;
    paint.height = height;
    const context = paint.getContext('2d');
    const background = context.createRadialGradient(width * 0.45, height * 0.35, 20, width / 2, height / 2, width * 0.7);
    background.addColorStop(0, ['#4a3a22', '#3a2a1c', '#2c3024'][seed % 3]);
    background.addColorStop(1, '#0d0906');
    context.fillStyle = background;
    context.fillRect(0, 0, width, height);
    const cx = width * (0.44 + random() * 0.12);
    const headY = height * 0.4;
    context.fillStyle = ['#1a120c', '#21160f', '#15110d'][seed % 3];
    context.beginPath();
    context.ellipse(cx, height * 0.98, width * 0.3, height * 0.36, 0, Math.PI, 0);
    context.fill();
    context.fillStyle = '#6b5039';
    context.beginPath();
    context.ellipse(cx, headY, 40, 52, 0, 0, Math.PI * 2);
    context.fill();
    context.fillStyle = 'rgba(20, 12, 8, 0.75)';
    context.beginPath();
    context.ellipse(cx, headY - 34, 46, 30, 0, Math.PI, 0);
    context.fill();
    const eyeY = headY - 6;
    const eyes = [cx - 15, cx + 15];
    for (const x of eyes) {
        context.fillStyle = '#d9cfb0';
        context.beginPath();
        context.ellipse(x, eyeY, 6.5, 3.2, 0, 0, Math.PI * 2);
        context.fill();
        context.fillStyle = '#120a06';
        context.beginPath();
        context.arc(x + (random() - 0.5) * 2, eyeY, 2.4, 0, Math.PI * 2);
        context.fill();
    }
    context.fillStyle = 'rgba(40, 20, 10, 0.6)';
    context.fillRect(cx - 12, headY + 22, 24, 4);
    for (let index = 0; index < 1400; index++) {
        context.fillStyle = `rgba(${random() > 0.5 ? '255, 230, 180' : '0, 0, 0'}, ${random() * 0.05})`;
        context.fillRect(random() * width, random() * height, 1 + random() * 3, 1 + random() * 3);
    }
    context.fillStyle = 'rgba(120, 90, 30, 0.12)';
    context.fillRect(0, 0, width, height);

    const glow = document.createElement('canvas');
    glow.width = width;
    glow.height = height;
    const glowContext = glow.getContext('2d');
    glowContext.fillStyle = '#000';
    glowContext.fillRect(0, 0, width, height);
    glowContext.fillStyle = '#fff';
    for (const x of eyes) {
        glowContext.beginPath();
        glowContext.ellipse(x, eyeY, 5.5, 2.6, 0, 0, Math.PI * 2);
        glowContext.fill();
    }
    return { map: canvasTexture(paint), emissiveMap: canvasTexture(glow) };
}

function createMaterials() {
    const carpet = loadTexture('/graphics/hotel/carpet.webp');
    const damask = loadTexture('/graphics/hotel/damask.webp');
    const plaster = loadTexture('/graphics/hotel/plaster.webp');
    const door = loadTexture('/graphics/hotel/door.webp', { repeat: false });
    for (const texture of [carpet, damask, plaster]) texture.anisotropy = 8;

    const materials = {
        wall: new THREE.MeshStandardMaterial({ color: 0xe6dccb, map: plaster, roughness: 0.92 }),
        ceiling: new THREE.MeshStandardMaterial({ color: 0xefe7d8, map: plaster, roughness: 0.95 }),
        carpet: new THREE.MeshStandardMaterial({ color: 0xffffff, map: carpet, roughness: 1 }),
        damask: new THREE.MeshStandardMaterial({ color: 0xffffff, map: damask, roughness: 0.78 }),
        trim: new THREE.MeshStandardMaterial({ color: 0xf2ede2, roughness: 0.62 }),
        door: new THREE.MeshStandardMaterial({ color: 0xffffff, map: door, roughness: 0.58 }),
        gilt: new THREE.MeshStandardMaterial({ color: 0xc79d52, roughness: 0.36, metalness: 0.25 }),
        shadow: new THREE.MeshStandardMaterial({ color: 0x24160d, roughness: 0.8 }),
        plate: new THREE.MeshStandardMaterial({ map: createRoomNumberAtlas(), roughness: 0.35, metalness: 0.2 }),
        lamp: new THREE.MeshBasicMaterial({ color: 0xffe3b8 }),
        exit: new THREE.MeshBasicMaterial({ map: createExitTexture() }),
    };
    for (const key of ['wall', 'ceiling', 'carpet', 'damask', 'trim', 'door', 'lamp']) {
        enhanceMaterialWithDarkness(materials[key]);
        darkenableMaterials.push(materials[key]);
    }
    return materials;
}

function createGeometry() {
    const dome = new THREE.SphereGeometry(0.3, 24, 8, 0, Math.PI * 2, Math.PI / 2, Math.PI / 2);
    dome.scale(1, 0.45, 1);
    return { dome };
}

function prepareModel(scene, scale, brighten = 1) {
    if (!scene) return null;
    scene.scale.setScalar(scale);
    scene.traverse((child) => {
        if (!child.isMesh) return;
        child.castShadow = true;
        child.receiveShadow = true;
        for (const material of Array.isArray(child.material) ? child.material : [child.material]) {
            // Metals read as black without an environment map; keep them diffuse enough for baked light.
            material.metalness = Math.min(material.metalness ?? 0, 0.3);
            material.envMapIntensity = 0;
            material.color.multiplyScalar(brighten);
        }
    });
    return scene;
}

// Swap the landscape canvas of the picture-frame model for a watching portrait.
function createPortraitModels(painting) {
    if (!painting) return [];
    const models = [];
    for (let variant = 0; variant < PORTRAIT_VARIANTS; variant++) {
        const { map, emissiveMap } = createPortrait(variant + 1);
        const portrait = painting.clone();
        portrait.traverse((child) => {
            if (!child.isMesh || !/canvas/i.test(child.material.name)) return;
            child.material = new THREE.MeshStandardMaterial({
                map,
                emissiveMap,
                emissive: 0xff3318,
                emissiveIntensity: 0,
                roughness: 0.7,
            });
            portraitMaterials.push(child.material);
        });
        models.push(portrait);
    }
    return models;
}

export function loadHotelAssets() {
    loading ??= Promise.all([
        loadGltfScene('/models/hotel/painting.glb'),
        loadGltfScene('/models/hotel/house-phone.glb'),
        loadGltfScene('/models/hotel/grandfather-clock.glb'),
        loadGltfScene('/models/hotel/console-table.glb'),
    ]).then(([painting, phone, clock, consoleTable]) => {
        const paintingModel = prepareModel(painting, 1.5);
        resources = {
            materials: createMaterials(),
            geometry: createGeometry(),
            models: {
                painting: paintingModel,
                portraits: createPortraitModels(paintingModel),
                phone: prepareModel(phone, 1.25),
                clock: prepareModel(clock, 1),
                // The scanned console is black lacquer; lift it to read as dark mahogany.
                console: prepareModel(consoleTable, 1, 2.6),
            },
        };
    });
    return loading;
}

export function getHotelResources() {
    return resources;
}

// Stable list: the runtime passes it to the entity every frame.
export function getHotelMaterials() {
    return darkenableMaterials;
}

// The portraits' eyes catch the light as sanity slips below half.
export function updatePortraitEyes(sanity) {
    const intensity = sanity >= 50 ? 0 : (1 - sanity / 50) * 2.4;
    for (const material of portraitMaterials) material.emissiveIntensity = intensity;
}
