export const DEFAULT_LEVEL_ID = 'lobby';

export const BACKROOM_LEVELS = [
    {
        id: 'lobby',
        badge: 'Level 0 / Survival',
        callToAction: 'Enter Level 0',
        detailTitle: 'Level 0: The Lobby',
        detailSubtitle: 'The fluorescent maze that never lets you settle.',
        menuLabel: 'The Lobby',
        menuStatus: 'Signal detected',
        objective: 'Connect three different telephone lines to guide a rescue signal to your location. Each call restores 25 sanity.',
        summary: 'The classic yellow-office sprawl. Endless turns. Buzzing lights. A telephone hidden deeper than it should be.',
        teaser: 'A procedural labyrinth of damp carpet, paper walls, and stale electric light.',
        detailParagraphs: [
            'Level 0 is the baseline nightmare: endless office partitions, long sightlines, and just enough repetition to make every turn feel wrong.',
            'Follow the ringing and watch your receiver. Connect three different phones before your sanity fades. Run when you must, and let your torch recharge when you can.',
        ],
        features: [
            'Endless connected rooms, forgotten signs, and distant footsteps.',
            'Three transmissions, a way out, and something watching.',
            'Sprint stamina, a rechargeable torch, and a gentler Wander mode.',
        ],
        theme: {
            accent: '#d9c98a',
            ambientLightColor: 0xd7d3a2,
            ambientLightIntensity: 0.025,
            ceilingColor: 0xbbbbbb,
            fogColor: 0x333322,
            fogDensity: 0.028,
            floorColor: 0xa9a865,
            lightPanelColor: 0xffffff,
            sceneBackground: 0x050503,
            wallColor: 0xffffff,
        },
    },
    {
        id: 'hotel',
        badge: 'Theme Preview',
        callToAction: 'Enter Hotel Drift',
        detailTitle: 'Hotel Drift',
        detailSubtitle: 'Vacant corridors, old carpet, and doors that never open the same way twice.',
        menuLabel: 'Hotel Rooms',
        menuStatus: 'Preview Route',
        objective: 'Cross the dim hotel ring and reach a service phone before the silence turns sentient.',
        summary: 'A warmer, tighter backroom variant inspired by abandoned hotel hallways and sealed guest rooms.',
        teaser: 'Burgundy shadows, brass reflections, and a corridor that feels too polite to be safe.',
        detailParagraphs: [
            'Hotel Drift shifts the same procedural runtime into an abandoned hospitality shell. The walls darken, the light warms, and the maze feels more intimate and more predatory.',
            'The geometry still follows the current chunk system, but the theme, tone, and onboarding copy are already separated so a custom hotel ruleset can drop in cleanly later.',
        ],
        features: [
            'Dedicated level-selection tile and detail screen.',
            'Level-specific scene palette, lighting, and menu tone.',
            'Architecture ready for custom hotel assets and rules.',
        ],
        theme: {
            accent: '#d88966',
            ambientLightColor: 0xc7a07c,
            ambientLightIntensity: 0.025,
            ceilingColor: 0x8e7d73,
            fogColor: 0x1f120f,
            fogDensity: 0.026,
            floorColor: 0x5d2e28,
            lightPanelColor: 0xffe1b8,
            sceneBackground: 0x090504,
            wallColor: 0xd7b2a4,
        },
    },
    {
        id: 'pools',
        badge: 'Theme Preview',
        callToAction: 'Enter Pool Complex',
        detailTitle: 'Pool Complex',
        detailSubtitle: 'Blue echo, tiled glare, and too much space between each ripple.',
        menuLabel: 'Pool Rooms',
        menuStatus: 'Preview Route',
        objective: 'Push through the chlorine-blue maze and find a dry line out before the reflections start moving first.',
        summary: 'A cold, tiled variant inspired by the Backrooms pool rooms: open chambers, damp light, and impossible depth.',
        teaser: 'Aquatic light, pale tile, and a horizon made of echoes instead of walls.',
        detailParagraphs: [
            'Pool Complex re-skins the current procedural maze into a colder, wetter atmosphere. The same runtime now loads a different backroom identity instead of a single fixed look.',
            'This is the staging ground for future pool-specific geometry, reflections, and acoustics. The selection flow and runtime switch are already in place.',
        ],
        features: [
            'Dedicated level-selection tile and detail screen.',
            'Level-specific palette, fog, and lighting setup.',
            'Ready for future water, tile, and room-scale generation changes.',
        ],
        theme: {
            accent: '#8fd5dd',
            ambientLightColor: 0x9fd6df,
            ambientLightIntensity: 0.025,
            ceilingColor: 0xc7ecef,
            fogColor: 0x163740,
            fogDensity: 0.018,
            floorColor: 0x4a97a6,
            lightPanelColor: 0xe8feff,
            sceneBackground: 0x031215,
            wallColor: 0xbce7ee,
        },
    },
];

export function getLevelById(levelId) {
    return BACKROOM_LEVELS.find((level) => level.id === levelId) ?? BACKROOM_LEVELS[0];
}
